
<div id="page-bgtop">
<div id="page-wrapper">
        <div id="page-bgbtm">
            <div id="page" class="5grid-layout">
                <div id="page-content-wrapper">
                            <section>
                                <div>
                                    <h2>Contact Form</h2>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('battle', array('action' => 'contact')));
$form->prepare();
// $this->form()->openTag($form);
// $this->formRow( $form->get('submit'));


// echo $this->form()->openTag($form);
// // echo $this->formHidden($form->get('id'));
// // echo $this->formRow($form->get('title'));
// // echo $this->formRow($form->get('artist'));
// echo $this->formSubmit($form->get('submit'));
// echo $this->form()->closeTag();

echo $this->form()->render($form);
?>
                                    <p class="subtitle">Donec leo, vivamus fermentum nibh in augue praesent a lacus</p>
                                <a href="#"><img src="/images/pics03.jpg" alt=""></a>
                                </div>
                            </section>
                </div>
            </div>
        </div>
    </div>
</div>
