
<div id="page-bgtop">
<div id="page-wrapper">
        <div id="page-bgbtm">
            <div id="page" class="5grid-layout">
                <div id="page-content-wrapper">
                            <section>
                                <div>
                                    <h2>Contact Form</h2>

After fighting for over an hour to create a form reading through 
http://framework.zend.com/manual/2.0/en/user-guide/forms-and-actions.html 
and  http://framework.zend.com/manual/2.0/en/modules/zend.form.elements.html
I couldn't manage to create a working version
<br>
                                    <p class="subtitle">Donec leo, vivamus fermentum nibh in augue praesent a lacus</p>
                                <a href="#"><img src="/images/pics03.jpg" alt=""></a>
                                </div>
                            </section>
                </div>
            </div>
        </div>
    </div>
</div>
