    <div id="page-bgtop">
<div id="page-wrapper">
        <div id="page-bgbtm">
            <div id="page" class="5grid-layout">
                <div id="page-content-wrapper">
                    <div class="row">
                        <div class="12u">
                            <div id="banner"><a href="#">
                            <img src="/images/pics01.jpg" alt="">
                            </a></div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="12u">
                            <div class="row">
                                <div class="8u">
                                    <section id="content">
                                        <h2>Integer gravida nibh quis urna</h2>
                                        <p class="subtitle">Donec leo, vivamus fermentum nibh in augue praesent a lacus at urna</p>
                                        <p><a href="#"><img src="/images/pics02.jpg" alt=""></a></p>
                                        <p>Welcome to <strong>Aqueous</strong>, a free responsive HTML5 website template designed by <a href="http://html5templates.com/">HTML5Templates.com</a>.   It features a neat and clean color combination, a spacious content area, and a large banner area, making it a great design for a corporate/portfolio type of website.  And like all of our templates, it is built on HTML5 and CSS3, has full responsive support for desktops, tablets, and mobile devices, and is 100% free to use personally or commercially under the <a href="http://html5templates.com/license/">Creative Commons license</a>. Be sure to check out our <a href="http://html5templates.com/">website</a> for more awesome free HTML5 templates and follow us on <a href="http://twitter.com/HTML5T">Twitter</a> for updates and new releases! Enjoy!</p>
                                        <p class="button-style"><a href="#">Read Full Article</a></p>
                                    </section>
                                </div>
                                <div class="4u">
                                    <section id="sidebar">
                                        <h2>Gravida nibh quis urna</h2>
                                        <p class="subtitle">praesent a lacus at urna</p>
                                        <ul class="style1">
                                            <li class="first">
                                                <p class="date"><a href="#">September<b>11</b></a></p>
                                                <p><a href="#">Donec leo, vivamus fermentum nibh in augue praesent a lacus at urna congue rutrum. Maecenas luctus lectus.</a></p>
                                            </li>
                                            <li>
                                                <p class="date"><a href="#">September<b>09</b></a></p>
                                                <p><a href="#">Donec leo, vivamus fermentum nibh in augue praesent a lacus at urna congue rutrum. Maecenas luctus lectus.</a></p>
                                            </li>
                                            <li>
                                                <p class="date"><a href="#">September<b>07</b></a></p>
                                                <p><a href="#">Donec leo, vivamus fermentum nibh in augue praesent a lacus at urna congue rutrum. Maecenas luctus lectus.</a></p>
                                            </li>
                                        </ul>
                                    </section>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>