<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Zen Monastery '. $this->translate('Battle in Zend'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))

                        ->prependStylesheet($this->basePath() . '/css/5grid/core.css')
                        ->prependStylesheet($this->basePath() . '/css/5grid/core-desktop.css')
                        ->prependStylesheet($this->basePath() . '/css/5grid/core-1200px.css')
                        ->prependStylesheet($this->basePath() . '/css/5grid/core-noscript.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/5grid/core-noscript.css')
                        ->prependStylesheet($this->basePath() . '/css/style-desktop.css'); ?>

        <!-- Scripts -->
        <?php echo $this->headScript()

            ->prependFile($this->basePath() . 'css/5grid/jquery.js')
            ->prependFile($this->basePath() . 'css/5grid/init.js?use=mobile,desktop,1000px&amp;mobileUI=1&amp;mobileUI.theme=none')
        ; ?>

    </head>
    <body>
<div id="header-wrapper">
    <header id="header">
        <div class="5grid-layout">
            <div class="row">
                <div class="12u" id="logo"> <!-- Logo -->
                    <h1><a href="#" class="mobileUI-site-name">PHP Frameworks Battle</a></h1>
                    <p><?php echo $this->translate('Skeleton Application') ?></p>
                </div>
            </div>
        </div>
        <div id="menu-wrapper">
            <div class="5grid-layout">
                <div class="row">
                    <div class="12u" id="menu">
                        <nav class="mobileUI-site-nav">
                            <ul>
                                <li class="current_page_item"><a href="index.html">Homepage</a></li>
                                <li><a href="contact.html">Contact</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </header>
</div>

        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
